#pragma once

#include "block.h"
#include "drawable.h"
#include <memory>

// Generated by ChatGPT
enum FaceDirection {
  Right,
  Left,
  Top,
  Bottom,
  Front,
  Back,
  NUM_FACES,
};

enum FaceAxis {
  AXIS_X,
  AXIS_Y,
  AXIS_Z,
  NUM_AXIS,
};

const glm::vec3 dirVectors[6] = {
    {1, 0, 0},  // Right
    {-1, 0, 0}, // Left
    {0, 1, 0},  // Up
    {0, -1, 0}, // Down
    {0, 0, 1},  // Front
    {0, 0, -1}  // Back
};

const glm::vec3 CubeFaces[6][6] = {
    // Right (+X)
    {{1.0f, 0.0f, 1.0f},
     {1.0f, 0.0f, 0.0f},
     {1.0f, 1.0f, 0.0f},

     {1.0f, 0.0f, 1.0f},
     {1.0f, 1.0f, 0.0f},
     {1.0f, 1.0f, 1.0f}},

    // Left (-X)
    {{0.0f, 0.0f, 0.0f},
     {0.0f, 0.0f, 1.0f},
     {0.0f, 1.0f, 1.0f},

     {0.0f, 0.0f, 0.0f},
     {0.0f, 1.0f, 1.0f},
     {0.0f, 1.0f, 0.0f}},

    // Up (+Y)
    {{0.0f, 1.0f, 1.0f},
     {1.0f, 1.0f, 1.0f},
     {1.0f, 1.0f, 0.0f},

     {0.0f, 1.0f, 1.0f},
     {1.0f, 1.0f, 0.0f},
     {0.0f, 1.0f, 0.0f}},

    // Down (-Y)
    {{0.0f, 0.0f, 0.0f},
     {1.0f, 0.0f, 0.0f},
     {1.0f, 0.0f, 1.0f},

     {0.0f, 0.0f, 0.0f},
     {1.0f, 0.0f, 1.0f},
     {0.0f, 0.0f, 1.0f}},

    // Front (+Z)
    {{0.0f, 0.0f, 1.0f},
     {1.0f, 0.0f, 1.0f},
     {1.0f, 1.0f, 1.0f},

     {0.0f, 0.0f, 1.0f},
     {1.0f, 1.0f, 1.0f},
     {0.0f, 1.0f, 1.0f}},

    // Back (-Z)
    {{1.0f, 0.0f, 0.0f},
     {0.0f, 0.0f, 0.0f},
     {0.0f, 1.0f, 0.0f},

     {1.0f, 0.0f, 0.0f},
     {0.0f, 1.0f, 0.0f},
     {1.0f, 1.0f, 0.0f}}
};

static const glm::vec3 FaceVertices[6][4] = {
  // Right +X
  {
    {1, 0, 0},
    {1, 0, 1},
    {1, 1, 1},
    {1, 1, 0}
  },

  // Left -X
  {
    {0, 0, 1},
    {0, 0, 0},
    {0, 1, 0},
    {0, 1, 1}
  },

  // Top +Y
  {
    {0, 1, 1},
    {1, 1, 1},
    {1, 1, 0},
    {0, 1, 0}
  },

  // Bottom -Y
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 0, 1},
    {0, 0, 1}
  },

  // Front +Z
  {
    {1, 0, 1},
    {0, 0, 1},
    {0, 1, 1},
    {1, 1, 1}
  },

  // Back -Z
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 1, 0},
    {0, 1, 0}
  }
};

class Mesher {
public:
  virtual std::shared_ptr<DrawableMesh>
  CreateMesh(const Block ***const blocks) = 0;

protected:
  // NOTE: may need to be marked virtual in the future
  void buildFace(const FaceDirection direction,
                 std::vector<glm::vec3> &vertices, const glm::vec3 offset);
};

// Assembles a complete mesh with no optimization
class MesherBasic : public Mesher {
public:
  std::shared_ptr<DrawableMesh>
  CreateMesh(const Block ***const blocks) override;
};

// Assembles a mesh by looping through all a block's neighbors
class MesherNaive : public Mesher {
public:
  std::shared_ptr<DrawableMesh>
  CreateMesh(const Block ***const blocks) override;
};
