#pragma once

#include "block.h"
#include "drawable_mesh.h"

// Generated by ChatGPT
enum FaceDirection {
  Right,
  Left,
  Top,
  Bottom,
  Front,
  Back,
  NUM_FACES,
};

constexpr glm::vec3 dirVectors[6] = {
  {1, 0, 0},  // right
  {-1, 0, 0}, // left
  {0, 1, 0},  // up
  {0, -1, 0}, // down
  {0, 0, 1},  // front
  {0, 0,-1}  // back
};

constexpr glm::vec3 CubeFaces[6][6] = {
    // Right (+X)
    {
        {1.0f, 0.0f, 1.0f},
        {1.0f, 0.0f, 0.0f},
        {1.0f, 1.0f, 0.0f},

        {1.0f, 0.0f, 1.0f},
        {1.0f, 1.0f, 0.0f},
        {1.0f, 1.0f, 1.0f}
    },

    // Left (-X)
    {
        {0.0f, 0.0f, 0.0f},
        {0.0f, 0.0f, 1.0f},
        {0.0f, 1.0f, 1.0f},

        {0.0f, 0.0f, 0.0f},
        {0.0f, 1.0f, 1.0f},
        {0.0f, 1.0f, 0.0f}
    },

    // Up (+Y)
    {
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 0.0f},

        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 0.0f},
        {0.0f, 1.0f, 0.0f}
    },

    // Down (-Y)
    {
        {0.0f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f},
        {1.0f, 0.0f, 1.0f},

        {0.0f, 0.0f, 0.0f},
        {1.0f, 0.0f, 1.0f},
        {0.0f, 0.0f, 1.0f}
    },

    // Front (+Z)
    {
        {0.0f, 0.0f, 1.0f},
        {1.0f, 0.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},

        {0.0f, 0.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        {0.0f, 1.0f, 1.0f}
    },

    // Back (-Z)
    {
        {1.0f, 0.0f, 0.0f},
        {0.0f, 0.0f, 0.0f},
        {0.0f, 1.0f, 0.0f},

        {1.0f, 0.0f, 0.0f},
        {0.0f, 1.0f, 0.0f},
        {1.0f, 1.0f, 0.0f}
    }
};

static const glm::vec3 FaceVertices[6][4] = {
  // Right +X
  {
    {1, 0, 0},
    {1, 0, 1},
    {1, 1, 1},
    {1, 1, 0}
  },

  // Left -X
  {
    {0, 0, 1},
    {0, 0, 0},
    {0, 1, 0},
    {0, 1, 1}
  },

  // Top +Y
  {
    {0, 1, 1},
    {1, 1, 1},
    {1, 1, 0},
    {0, 1, 0}
  },

  // Bottom -Y
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 0, 1},
    {0, 0, 1}
  },

  // Front +Z
  {
    {1, 0, 1},
    {0, 0, 1},
    {0, 1, 1},
    {1, 1, 1}
  },

  // Back -Z
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 1, 0},
    {0, 1, 0}
  }
};

class Mesher {
public:
  virtual DrawableMesh CreateMesh(const Block ***const blocks) = 0;
};
