#pragma once

#include "block.h"
#include "chunk.h"
#include <array>
#include <glm/ext/vector_float3.hpp>
#include <vector>

struct vec3 {
public:
  int x, y, z;
};



// Generated by ChatGPT
enum  FaceDirection {
    Right,
    Left,
    Top,
    Bottom,
    Front,
    Back
};

constexpr vec3 dirs[6] = {
    {1, 0, 0},  // right
    {-1, 0, 0}, // left
    {0, 1, 0},  // up
    {0, -1, 0}, // down
    {0, 0, 1},  // front
    {0, 0, -1}  // back
};

static const glm::vec3 FaceVertices[6][4] = {
  // Right +X
  {
      {1, 0, 0},
      {1, 0, 1},
      {1, 1, 1},
      {1, 1, 0}
  },

  // Left -X
  {
      {0, 0, 1},
      {0, 0, 0},
      {0, 1, 0},
      {0, 1, 1}
  },

  // Top +Y
  {
      {0, 1, 1},
      {1, 1, 1},
      {1, 1, 0},
      {0, 1, 0}
  },

  // Bottom -Y
  {
      {0, 0, 0},
      {1, 0, 0},
      {1, 0, 1},
      {0, 0, 1}
  },

  // Front +Z
  {
      {1, 0, 1},
      {0, 0, 1},
      {0, 1, 1},
      {1, 1, 1}
  },

  // Back -Z
  {
      {0, 0, 0},
      {1, 0, 0},
      {1, 1, 0},
      {0, 1, 0}
  }
};

class NaiveMesher {
public:
  void Mesh(Block ***blocks) {
    for (int x = 0; x < CHUNK_SIZE; x++)
      for (int y = 0; y < CHUNK_SIZE; y++)
        for (int z = 0; z < CHUNK_SIZE; z++) {
          auto &block = blocks[x][y][z];

          if (block.GetBlockType() == BlockType_Air)
            continue;

          // TODO: Need to add edge cases for boundaries
          for (const auto &direction : dirs) {
            const auto &neighborBlock =
                blocks[x + direction.x][y + direction.y][z + direction.z];

            if (neighborBlock.GetBlockType() != BlockType_Air) {
              // emit face in direction
            }
          }
        }
  }

  void buildFace(const FaceDirection direction) {
    std::vector<glm::vec3> vertices{};

    // Take dirFace by ref so that it preserves array info
    const auto &dirFace = FaceVertices[direction];

    for (const auto &vec : dirFace) {
      vertices.push_back(vec);
    }
  }
};
