#pragma once

#include "block.h"
#include "chunk.h"
#include <glm/ext/vector_float3.hpp>
#include <vector>

// Generated by ChatGPT
enum FaceDirection {
  Right,
  Left,
  Top,
  Bottom,
  Front,
  Back,
  NUM_FACES,
};

const glm::vec3 dirVectors[6] = {
  {1, 0, 0},  // right
  {-1, 0, 0}, // left
  {0, 1, 0},  // up
  {0, -1, 0}, // down
  {0, 0, 1},  // front
  {0, 0, -1}  // back
};

static const glm::vec3 FaceVertices[6][4] = {
  // Right +X
  {
    {1, 0, 0},
    {1, 0, 1},
    {1, 1, 1},
    {1, 1, 0}
  },

  // Left -X
  {
    {0, 0, 1},
    {0, 0, 0},
    {0, 1, 0},
    {0, 1, 1}
  },

  // Top +Y
  {
    {0, 1, 1},
    {1, 1, 1},
    {1, 1, 0},
    {0, 1, 0}
  },

  // Bottom -Y
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 0, 1},
    {0, 0, 1}
  },

  // Front +Z
  {
    {1, 0, 1},
    {0, 0, 1},
    {0, 1, 1},
    {1, 1, 1}
  },

  // Back -Z
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 1, 0},
    {0, 1, 0}
  }
};

class NaiveMesher {
public:
  // TODO: This should return a drawable_mesh!
  std::vector<glm::vec3> MeshBlocks(Block ***blocks) {
    std::vector<glm::vec3> vertices;

    for (int x = 0; x < CHUNK_SIZE; x++)
      for (int y = 0; y < CHUNK_SIZE; y++)
        for (int z = 0; z < CHUNK_SIZE; z++) {
          const auto &block = blocks[x][y][z];

          if (block.GetBlockType() == BlockType_Air)
            continue;

          // TODO: Need to add edge cases for boundaries

          // Have to iterate over an enum.... no clean way to do it
          for (int i = Right; i < NUM_FACES; i++) {
            const auto &dirVector = dirVectors[i];

            const auto &neighborBlock =
                blocks[x + static_cast<int>(dirVector.x)]
                      [y + static_cast<int>(dirVector.y)]
                      [z + static_cast<int>(dirVector.z)];

            if (neighborBlock.GetBlockType() == BlockType_Air) {
              // may god smite me down for this code
              buildFace(static_cast<FaceDirection>(i), vertices,
                        glm::vec3(x, y, z));
            }
          }
        }

    return vertices;
  }

private:
  // TODO: Need to add an offset for each xyz coord
  void buildFace(const FaceDirection direction,
                 std::vector<glm::vec3> &vertices, const glm::vec3 offset) {
    // Take dirFace by ref so that it preserves array info
    const auto &dirFace = FaceVertices[direction];

    for (const auto &vec : dirFace) {
      const glm::vec3 newFace = vec + offset;

      vertices.push_back(newFace);
    }
  }
};
