#include "glm/vec3.hpp"

// Generated by ChatGPT
enum FaceDirection {
  FACE_RIGHT,
  FACE_LEFT,
  FACE_TOP,
  FACE_BOTTOM,
  FACE_FRONT,
  FACE_BACK,
  NUM_FACES,
};

enum CoordinateIndex {
  COORDINATE_X,
  COORDINATE_Y,
  COORDINATE_Z,
  NUM_COORDINATES,
};

const glm::ivec3 dirVectors[6] = {
    {1, 0, 0},  // Right
    {-1, 0, 0}, // Left
    {0, 1, 0},  // Up
    {0, -1, 0}, // Down
    {0, 0, 1},  // Front
    {0, 0, -1}  // Back
};

const glm::vec3 CubeFaces[6][6] = {
    // Right (+X)
    {{1.0f, 0.0f, 1.0f},
     {1.0f, 0.0f, 0.0f},
     {1.0f, 1.0f, 0.0f},

     {1.0f, 0.0f, 1.0f},
     {1.0f, 1.0f, 0.0f},
     {1.0f, 1.0f, 1.0f}},

    // Left (-X)
    {{0.0f, 0.0f, 0.0f},
     {0.0f, 0.0f, 1.0f},
     {0.0f, 1.0f, 1.0f},

     {0.0f, 0.0f, 0.0f},
     {0.0f, 1.0f, 1.0f},
     {0.0f, 1.0f, 0.0f}},

    // Up (+Y)
    {{0.0f, 1.0f, 1.0f},
     {1.0f, 1.0f, 1.0f},
     {1.0f, 1.0f, 0.0f},

     {0.0f, 1.0f, 1.0f},
     {1.0f, 1.0f, 0.0f},
     {0.0f, 1.0f, 0.0f}},

    // Down (-Y)
    {{0.0f, 0.0f, 0.0f},
     {1.0f, 0.0f, 0.0f},
     {1.0f, 0.0f, 1.0f},

     {0.0f, 0.0f, 0.0f},
     {1.0f, 0.0f, 1.0f},
     {0.0f, 0.0f, 1.0f}},

    // Front (+Z)
    {{0.0f, 0.0f, 1.0f},
     {1.0f, 0.0f, 1.0f},
     {1.0f, 1.0f, 1.0f},

     {0.0f, 0.0f, 1.0f},
     {1.0f, 1.0f, 1.0f},
     {0.0f, 1.0f, 1.0f}},

    // Back (-Z)
    {{1.0f, 0.0f, 0.0f},
     {0.0f, 0.0f, 0.0f},
     {0.0f, 1.0f, 0.0f},

     {1.0f, 0.0f, 0.0f},
     {0.0f, 1.0f, 0.0f},
     {1.0f, 1.0f, 0.0f}}
};

static const glm::vec3 FaceVertices[6][4] = {
  // Right +X
  {
    {1, 0, 0},
    {1, 0, 1},
    {1, 1, 1},
    {1, 1, 0}
  },

  // Left -X
  {
    {0, 0, 1},
    {0, 0, 0},
    {0, 1, 0},
    {0, 1, 1}
  },

  // Top +Y
  {
    {0, 1, 1},
    {1, 1, 1},
    {1, 1, 0},
    {0, 1, 0}
  },

  // Bottom -Y
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 0, 1},
    {0, 0, 1}
  },

  // Front +Z
  {
    {1, 0, 1},
    {0, 0, 1},
    {0, 1, 1},
    {1, 1, 1}
  },

  // Back -Z
  {
    {0, 0, 0},
    {1, 0, 0},
    {1, 1, 0},
    {0, 1, 0}
  }
};
